{{- range $i := until (int .Values.nodeCount) }}
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachine
metadata:
  name: rke2-node-{{ add $i 1 }}-{{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: rke2-ha-cluster
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        harvesterhci.io/volumeClaimTemplates: |
          - metadata:
              name: "rke2-node-{{ add $i 1 }}-{{ $.Release.Name }}-disk"
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: {{ $.Values.vm.diskSize }}
              source:
                pvcName: {{ $.Values.image.name }}
                pvcNamespace: {{ $.Values.image.namespace }}
    spec:
      domain:
        cpu:
          cores: {{ $.Values.vm.cpu }}
        memory:
          guest: {{ $.Values.vm.memory }}
        devices:
          disks:
            - name: disk-0
              bootOrder: 1
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            - name: nic-0
              model: virtio
              bridge: {}
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: "rke2-node-{{ add $i 1 }}-{{ $.Release.Name }}-disk"
        - name: cloudinit
          cloudInitNoCloud:
            userData: |
              #cloud-config
              users:
                - name: ubuntu
                  ssh-authorized-keys:
                    - {{ $.Values.sshPublicKey }}
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  groups: sudo
                  shell: /bin/bash
              write_files:
                - path: /etc/rancher/rke2-config/config.yaml
                  permissions: "0644"
                  content: |
                    {{ $.Files.Get "rke2-config.yaml" | indent 20 }}
                - path: /etc/rancher/rke2-config/install.sh
                  permissions: "0755"
                  content: |
                    {{ $.Files.Get "install-script.yaml" | indent 20 | regexReplaceAll ".*install.sh: |" "" }}
             runcmd:
               - - mkdir
                 - -p
                 - /etc/rancher/rke2-config
               - - cp
                 - /etc/rancher/rke2-config/config.yaml
                 - /etc/rancher/rke2-config/rke2-config.yaml
               - - bash
                 - /etc/rancher/rke2-config/install.sh
                 - {{ if eq $i 0 }}1{{ else }}0{{ end }}
                 - {{ $i }}
      networks:
        - name: nic-0
          multus:
            networkName: {{ $.Values.network.name }}
---
{{- end }}
