nodeCount: 3  # Adjust if you want more or fewer nodes
rke2:
  version: v1.30.5+rke2r1
  channel: stable
  type: server
kubeVip:
  version: v0.4.2
  vip: "YOUR_VIP"  # e.g., "192.168.1.100"
  interface: "YOUR_INTERFACE"  # e.g., "eth0" (check with `ip link`)
network:
  staticIps:
    - "YOUR_IP_1"  # e.g., "192.168.1.10"
    - "YOUR_IP_2"  # e.g., "192.168.1.11"
    - "YOUR_IP_3"  # e.g., "192.168.1.12"
  domain: "YOUR_DOMAIN"  # e.g., "example.com"
  clusterDomain: "YOUR_CLUSTER_DOMAIN"  # e.g., "rancher-cluster.example.com"
rancher:
  hostname: "YOUR_CLUSTER_DOMAIN"  # Match clusterDomain above
  bootstrapPassword: "admin"  # Change if desired
  certPath: "abc.cert"
  keyPath: "abc.key"
  caPath: "cacerts.pem"
