# Harvester VM settings
nodeCount: 3
image:
  namespace: default
  name: ubuntu-20.04  # Replace with your Harvester image name
network:
  name: vlan1  # Replace with your Harvester VLAN network name
  interface: ens3
vm:
  cpu: 2
  memory: 4Gi
  diskSize: 20Gi

# RKE2 settings
rke2:
  version: v1.30.5+rke2r1

# Kube-VIP settings
kubeVip:
  version: v0.8.0
  vip: "10.31.42.100"
  interface: "ens3"

# Rancher settings
rancher:
  hostname: "rancher-cluster.example.com"
  domain: "example.com"

# SSH key (replace with your public key)
sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2E... user@host"
