---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-rancher-ingress
  namespace: cattle-system
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.rancher.certPath | b64enc }}
  tls.key: {{ .Files.Get .Values.rancher.keyPath | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-ca
  namespace: cattle-system
data:
  cacerts.pem: {{ .Files.Get .Values.rancher.caPath | b64enc }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: cattle-system
spec:
  chart: rancher
  repo: https://charts.rancher.com/server-charts/prime
  targetNamespace: cattle-system
  valuesContent: |
    hostname: {{ .Values.rancher.hostname }}
    bootstrapPassword: {{ .Values.rancher.bootstrapPassword }}
    ingress:
      tls:
        source: secret
        secretName: tls-rancher-ingress
    privateCA: true
